[package]
name = "optimizer"
version = "0.0.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

compiler = { path = "../compiler" }
parser = { path = "../parser" }

fnv = "1.0.6"
