[package]
name = "errors"
version = "0.0.7"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ariadne = "0.1.3" # errors
internment = "0.5.4"

shared = { path = "../shared" }
